name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: |
        npm run install:all
        
    - name: Run backend tests
      run: |
        cd backend
        npm test
        
    - name: Run web frontend tests
      run: |
        cd frontend/web
        npm test
        
    - name: Build web frontend
      run: |
        cd frontend/web
        npm run build 